services:
  - type: web
    name: ats-workorder-api
    runtime: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '4000'
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: COOKIE_SAME_SITE
        value: none
      - key: STORAGE_REGION
        sync: false
      - key: STORAGE_ENDPOINT
        sync: false
      - key: STORAGE_BUCKET
        sync: false
      - key: STORAGE_ACCESS_KEY
        sync: false
      - key: STORAGE_SECRET_KEY
        sync: false
